### ISSUE TITLE
SimpleArea 오류

### ISSUE THREAD

**Issue by cloud9350** [if-Team/Personal#3]
"/SimpleArea.phar/src/SimpleArea/SimpleArea_Database" at line 231
12:32:04 [CRITICAL] Could not pass event pocketmine\event\player\PlayerInteractEvent to SimpleArea v0.10-alpha: Undefined offset: 1 on SimpleArea\SimpleArea
12:32:04 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/SimpleArea.phar/src/SimpleArea/SimpleArea_Database" at line 231
12:32:04 [CRITICAL] Could not pass event pocketmine\event\block\BlockPlaceEvent to SimpleArea v0.10-alpha: Undefined offset: 1 on SimpleArea\SimpleArea
12:32:04 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/SimpleArea.phar/src/SimpleArea/SimpleArea_Database" at line 231
12:32:08 [CRITICAL] Could not pass event pocketmine\event\block\BlockPlaceEvent to SimpleArea v0.10-alpha: Undefined offset: 1 on SimpleArea\SimpleArea
12:32:08 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/SimpleArea.phar/src/SimpleArea/SimpleArea_Database" at line 231
12:32:10 [CRITICAL] Could not pass event pocketmine\event\player\PlayerInteractEvent to SimpleArea v0.10-alpha: Undefined offset: 1 on SimpleArea\SimpleArea
12:32:10 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/SimpleArea.phar/src/SimpleArea/SimpleArea_Database" at line 231
12:32:10 [CRITICAL] Could not pass event pocketmine\event\block\BlockPlaceEvent to SimpleArea v0.10-alpha: Undefined offset: 1 on SimpleArea\SimpleArea
12:32:10 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/SimpleArea.phar/src/SimpleArea/SimpleArea_Database" at line 231
12:32:14 [CRITICAL] Could not pass event pocketmine\event\block\BlockPlaceEvent to SimpleArea v0.10-alpha: Undefined offset: 1 on SimpleArea\SimpleArea
12:32:14 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/SimpleArea.phar/src/SimpleArea/SimpleArea_Database" at line 231
12:32:15 [CRITICAL] Could not pass event pocketmine\event\player\PlayerInteractEvent to SimpleArea v0.10-alpha: Undefined offset: 1 on SimpleArea\SimpleArea
12:32:15 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/SimpleArea.phar/src/SimpleArea/SimpleArea_Database" at line 231
12:32:15 [CRITICAL] Could not pass event pocketmine\event\block\BlockPlaceEvent to SimpleArea v0.10-alpha: Undefined offset: 1 on SimpleArea\SimpleArea
12:32:15 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/SimpleArea.phar/src/SimpleArea/SimpleArea_Database" at line 231

블럭 하나하나 놓을때마다 보호가 안되고 이런 오류가 뜹니다.

플러그인 목록
NightPVP v2.0.1, FurnaceIndicator v1.0, ItemCode v0, MoreHealth v1.0.3, SimpleAuth v1.6.0, SimpleArea v0.10-alpha, WorldEditArt v1.0.0_beta_dev_#044, Whois v1.1.4, Farms v1.1-alpha, SignStatus v1.1.2, GameModeKick v1.0-alpha, ArmorSpawn v2.0, OreFinder v1, PurePerms v1.0.3, WorldBorder v1.0.0, KeepInventory v1.2.0, VoteReward v2.1, GoodMorning v1.0-alpha, Universe v1.0.0, ChestGuard v1.1-alpha, SignCommand v1.0-alpha, GreenBelt v1.0-alpha, MoreCommands v1.0.2, iControlU v1.3, BigBrother v1.4.0-beta, PureChat v1.2.0

환경은 CentOS 64bit입니다.

아, 혹시나 싶어서 적어두는데 sethome 하는 순간부터 저 오류가 뜹니다..

**Comment by HmHmmHm** [comment]
에러보고 양식을 갖춰서 작성해주세요,
pocketmine.yml에서 멀티월드 처리오류입니다
