### ISSUE TITLE
플러그인 위시리스트 - 아이디어 리스트

### ISSUE THREAD

**Issue by HmHmmHm** [if-Team/Personal#4]
<h1> 이 페이지는 뭔가요? 페이지 안내!

이 페이지는 플러그인에 원하는 기능을 요청하거나
원하는 플러그인을 요청하는 페이지 입니다!

원하시는 플러그인이 있으면 여기에 요청해보세요! (최대한 자세하게!)
(아래 게시물에 커멘트로 달아주시면 검토 후 차후 개발에 들어갑니다!)
(개발하는데 시간이 걸리므로 당장에 개발되지 않을 수도 있습니다)

**Comment by ns827** [comment]
자바로 PMMP 짜주세요 :P

**Comment by HmHmmHm** [comment]
@ns827 Blue Electric님에게...쿨렄렄

**Comment by Dolphin3203** [comment]
PC에
주민상점이라는 플러그인이 있는데
RPG아이탬과 혼합해서 사용할수 있습니다
주민상점은 아이탬을 원하는대로 교환하게 하는
예를들어 주민을 꾹 누른다던지 하면 설정창이 열리고
그 설정창에서 바꿀물건등을 설정하는 창이 열리고
설정을 다하면 주민상점이 되는 그런 플러그인이 있었으면 좋겠습니다
RPG아이탬도 그냥 수표 (화페) 용으로 만들면 좋겠습니다

**Comment by Dolphin3203** [comment]
+
스마트폰 PMMP용 자동재부팅 플러그인
이건 딱히 자세한 설명이 없어도...
giveall 플러그인
/giveall [아이탬코드] 치면 아이탬이 모두에게 나가는
플러그인

**Comment by XLVELA** [comment]
마인팜플러그인!
/is 또는 /땅생성 으로자신만의 땅을생성하고[스카이블럭]
자신만의땅에서 살아가는...플러그인이요!

**Comment by Dolphin3203** [comment]
위에분
+ 그거 심플에리어 내장 기능으로 좀있으면 나온데요..
그리고 구체적으로 해야할듯
/is,/섬 등등으로 섬을 생성하고
/is invite
/is kick
/is restart
등등의 명령어들들을 구체적으로 써야하실듯

**Comment by XLVELA** [comment]
쳇...돌핀님이너무자세하게써주셔버렸구만..그렇다면다른플러그인!
주기적으로상자리필[이미있는데쓰는법을잘..]+해당지역에만 특별한아이템이생기는플러그인이요!

**Comment by ebebebeb** [comment]
음..헝거게임플러그인에 한 1분동안 유저들이 월드에 들어오도록 대기해놓고 제한시간이 다 되면 아이템을 챙기러 가는 이런 기능ㅇ을 추가해주실수 있으신지~~시간나시면 봐주길 바랍니당~

**Comment by gmlwns** [comment]
내가원하는대로 명령어를 바꾸는 플러그인
/mymoney 라는명령어를
/명령어설정 mymoney <원하는명령어> 
로바꾸고 /명령어설정 mymoney 돈
으로하면 /돈 을쳐도 /mymoney 로쓸때와 똑같이 써지게하는플러그인 요청
/명령어설정 <명령어> <원하는명령어>

**Comment by ruddn0101** [comment]
일정시간마다 엔디티제거 컴마크에 ClearLag
플긴처럼

**Comment by rhrakaa1212** [comment]
안될 것 같지만 그래도 적어봅니다.
서버에서는 항상 먹고,캐고,자고 이것을 반봅합니다.
한마디로 지겹다... 이거죠.
그러니 서버에 브금을 추가하면 어떨까 생각합니다.
더욱 재미있고,즐거우며,더욱 신나게 플레이를 할 수 있죠.
이게 가능할지는 모르겠지만,한번 신청이라도 해봅니다.

**Comment by milgip123** [comment]
1. SimpleArea 에 땅크기를 여러개  수정가능하게 해주세요.(+가격)

**Comment by milgip123** [comment]
꽤 괜찮은 아이디어 있습니다

개인상점 플러그인 

/개인상점 

명령어입력시

상자,표지판이 주워진다

상자안에 물품넣기
상자위 표지판 설치


1.개인상점
2.가격
3.갯수:데미지
4.량
입력시 
설치완료했습니다  상점가격: ♡시간당 ♡원

상자 터치시 
이상자는 ♡♡님의 개인상점입니다
남은물품♡♡개

표지판 1회터치
♡♡물건을♡개♡돈으로 사시겠습니까
표지판 2회터치 
구매완료 

판매자 ♡♡님이 ♡♡아이탬을 구매하셨습니다 

한사람당 생성할수있는 상점 한계
설치시 드는비용 
시간당 드는비용

이렇게한다면 마인크래프트를 더욱 현실감있게 할수있을겁니다.

이상입니다

**Comment by milgip123** [comment]
SimpleArea  기능추가 [경매]

땅을 삽니다 
그땅을 몇일간 경매에 쓸수있습니다

땅위에서
                             (예: 천원씩 올라감)
/땅경매 <시작가격> <올라가는 돈> <마감시간>

이런식으로 적으면
1.땅경매
2.현재가격
3.1000
4.12시00분 마감

이표지판이 자동설치됩니다

이 위위 제가쓴글 보시면 이것이 실행되려면 제각각
땅크기,땅가격등 설정으로 실현 되야된다봅니다

ps. 돈없으면서 돈을 무한대로 땅을 경매하는 악질이 나올수있습니다

대비하여 누르자마자 돈이 빠지고 마감이 끝나면 돈을 다시받는 시스템이 있으면좋겠습니다

**Comment by ruddn0101** [comment]
칭호플러그인

/setprefix 로 채팅창 칭호설정
/delprefix 로 칭호삭제
/setnick 닉네임설정

**Comment by NoriDev** [comment]
서버접속시 마지막으로 접속한 곳에서 태어나게 가능한 플러그인이 있으면 좋겠습니다:)

**Comment by HmHmmHm** [comment]
@NoriDev 포켓마인 맵이름과 맵폴더명이 다를 때 생기는 에러입니다.
해당 맵폴더명또는 맵이름(nbt수정)을 통해서 해결하시기바랍니다.

**Comment by cooxcoox** [comment]
님 잠수유저 킥되는플긴 이 있었쓰면 좋겠습니다

**Comment by ChalkPE** [comment]
DEPRECATED : 이 저장소는 더 이상 사용되지 않습니다
