### ISSUE TITLE
에리어가드 플러그인

### ISSUE THREAD

**Issue by Dookong** [if-Team/Personal#5]
pmmp1.4에서는 호환되지 않는 에리어가드 플긴에 구역의 수정을 특정 플레이어에게만 허용하는 기능이 있습니다.RangeProtection이나 iprotector에서는 지원하지 않는 기능이죠ㅜㅜ
구역의 접근 권한을 개별적으로 부여할 수 있는 지역보호 플긴이 있었으면 좋겠습니다.

**Comment by HmHmmHm** [comment]
위시리스트에 작성하세요
(또한 클로즈-리오픈 시 알림이 가니 주의하세요)
(연속적 도배 시 깃헙 레포에서 차단 처리합니다)
